discord:
  bot-token: ${DISCORD_BOT_TOKEN}
  ranked-watcher:
    guild-id: ${DISCORD_GUILD_ID}
    webhook-url: ${DISCORD_CHANNEL_WEBHOOK_URL}
    avatar-url: ${DISCORD_AVATAR_URL}

riot:
  api-key: ${RIOT_API_KEY}
  region: europe

spring:
  data:
    mongodb:
      database: gsv-discord-tools
      authentication-database: admin
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      host: ${MONGO_HOST}

logging:
  level:
    root: warn
    de.lausi.gsvdiscordtools: info
