version: '3'

services:
  gsv-discord-tools:
    image: lausi95/gsv-discord-tools
    restart: always
    networks: [gsv-network]
    env_file: [gsv-discord-tools.env]
    ports:
      - "8081:8080"

  mongo-db:
    image: mongo
    restart: always
    networks: [gsv-network]
    env_file: [mongo.env]

networks:
  gsv-network:
